const productos = [
    {   id: 1,
        img: 'img/cm_brasil.png',
        marca: 'Café Martinez',
        variedad: 'Brasil 250grs',   
        precio: 900,
        cantidad: 1,
    }, 
    {  id: 2,
        img: 'img/cm_colombia.png',
        marca: 'Café Martinez',
        variedad: 'Colombia 250grs',   
        precio: 900,
        cantidad: 1,
    },
    {   id: 3,
        img: 'img/cm_decaf.png',
        marca: 'Café Martinez',
        variedad: 'Decaf 250grs',   
        precio: 1050,
        cantidad: 1,
        
    },
    {   id: 4, 
        img: 'img/cm_italiano.png',
        marca: 'Café Martinez',
        variedad: 'Italiano 250grs',   
        precio: 950,
        cantidad: 1,
     },
    {   id: 5,
        img: 'img/cm_selecto.png',
        marca: 'Café Martinez',
        variedad: 'Selecto 250grs',   
        precio: 1100,
        cantidad: 1,
     },
    {   id: 6,
        img: 'img/cm_suave.png',
        marca: 'Café Martinez',
        variedad: 'Suave 250grs',   
        precio: 750,
        cantidad: 1,
     }, 

    ]



